# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('artiste', '0002_auto_20170503_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='genre',
        ),
        migrations.AddField(
            model_name='artiste',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='genre.Genre'),
        ),
    ]
