# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapeUser', '0005_auto_20170503_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixtapeuser',
            name='fb_id',
        ),
    ]
