# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artiste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artiste.Artiste')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Genre')),
                ('mixtapeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
