# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste',
            name='artiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artiste.Artiste'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genre.Genre'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='mixtapeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
