# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0002_auto_20170503_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taste',
            name='artiste',
        ),
    ]
