# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixtapeUser', '0002_auto_20170423_1527'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='mixtapeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mixtapeUser.MixtapeUser'),
            preserve_default=False,
        ),
    ]
