# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170503_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_uri',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
